### ISSUE TITLE
Grafiken. Für alles.

### ISSUE THREAD

**Issue by MariusQuabeck** [MrKrisKrisu/toilet-paper-availability#8]
Moin, ich hätte gerne dynamisch generierte Statistiken auf der Seite zu allen Zahlen die so bei dir anfallen. Wöchentlicher Highscore pro Markt, welche Stadt am meisten kauft, einmal im Jahr ein automatisiertes Spiel in dem Städte unfreiwillig und automatisch gegeneinander antreten in mehreren Runden, etc :D 

(wontfix jaja)
🥂

**Comment by Jay16K** [comment]
Highscore Liste wäre ein Anfang, bzw. am besten gleich noch ein Lowscore.
Highscore der Durchsazstärksten Märkte?
